### PR TITLE
adds state section for onebox installation

### PR DESCRIPTION
**Pull request by mohit5it9**
https://github.com/Shippable/admiral/issues/1593

image

### CODE REVIEW

**Comment by ric03uec** [comment]
can you attach screenshot?

**Comment by mohit5it9** [comment]
@ric03uec 
image

**Comment by ric03uec** [comment]
why is it showing add new/existing nodes when dropdown says this node

**Comment by mohit5it9** [comment]
it's disabled. for all vault, rabbitMQ we have also done like this.
so you want to remove add section if "This node" is selected?

**Comment by ric03uec** [comment]
yes, this needs to be disabled

**Pull request merged**
