### PR TITLE
Adds redis install script for ubuntu 14.04 

### PR DESCRIPTION
**Pull request by scriptnull**
https://github.com/Shippable/admiral/issues/1895

Verified by directly running the script and trying out `INFO`, `SET`, `GET` commands on a fresh ubuntu 14.04 host machine.

### CODE REVIEW

**Comment by ric03uec** [comment]
please see how this is being done for u14 in current workflow and copy that file as is. i dont know why we're making changes to this script when we already have a script that works end to end

**Comment by scriptnull** [comment]
Redis official documentation recommends installing from source. Hence, I wrote the script the way it is now.


Furthermore, if I try to use apt-get install like we do in u14all ( https://github.com/dry-dock/u14all/blob/master/version/redis_4_0.sh )

The redis server seem to be unreachable
```
root@975d9d6a0a2a:/admiral/common/scripts/x86_64/Ubuntu_14.04/remote# redis-cli 
Could not connect to Redis at 127.0.0.1:6379: Connection refused
Could not connect to Redis at 127.0.0.1:6379: Connection refused
```

**Comment by ric03uec** [comment]
the rest of the script needs to change then. you cannot change the structure of the entire file. we need correct functions and naming conventions. if installation needs to change, only that part should change, nothing else

**Comment by scriptnull** [comment]
Here is what we have in u14all images

```bash
#!/bin/bash -e

echo "================= Installing redis-server ==================="

sudo add-apt-repository ppa:chris-lea/redis-server
sudo apt-get update
sudo wget https://redis.io/download
sudo apt-get install -q -y redis-server=4:4.0.8*
```

Here is what we have in my script
```bash
#!/bin/bash -e

export REDIS_VERSION="4.0.8"

sudo apt-get update
sudo apt-get install -y build-essential tcl8.5
wget http://download.redis.io/releases/redis-$REDIS_VERSION.tar.gz
tar xzf redis-$REDIS_VERSION.tar.gz
pushd redis-$REDIS_VERSION
  make
  make test
  sudo make install
  sudo REDIS_PORT=6379 \
    REDIS_CONFIG_FILE=/etc/redis/6379.conf \
    REDIS_LOG_FILE=/var/log/redis_6379.log \
    REDIS_DATA_DIR=/var/lib/redis/6379 \
    REDIS_EXECUTABLE=`command -v redis-server` ./utils/install_server.sh
popd
```

Except `sudo apt-get update` nothing is common here.

> we need correct functions and naming conventions. 

We already don't have any functions wrapping the existing logic. Should I wrap my logic around a function called `install_redis_server()`?

> if installation needs to change, only that part should change, nothing else

Could you be more specific on what _part_ needs to change here?

**Comment by ric03uec** [comment]
https://github.com/Shippable/admiral/blob/master/common/scripts/Ubuntu_14.04/installRedis.sh

**Comment by ric03uec** [comment]
this is not a drydock update, its admiral script

**Comment by scriptnull** [comment]
yeah ok. 

> please see how this is being done for u14 in current workflow and copy that file as is

I got confused that this statement meant to reuse the u14 script in drydock inside admiral. :sweat_smile: 

Is this the script that is going to call the OS specific `installRedis` script? 

https://github.com/Shippable/admiral/blob/f17d3ee5b112fd777f22be507980ea628e82b28f/common/scripts/installRedis.sh#L93-L95

If yes, could you tell me the way to test it? If not, we would need to set the value for `REDIS_HOST` and `REDIS_PORT` for our script to work.

https://github.com/Shippable/admiral/blob/f17d3ee5b112fd777f22be507980ea628e82b28f/common/scripts/Ubuntu_14.04/installRedis.sh#L38-L39

**Comment by ric03uec** [comment]
no, this is the script that gets copied over to the remote host and gets executed there

**Pull request merged**
